### ISSUE TITLE
bug :  incorrect g_game.getClientVersion() .lua .otui

### ISSUE THREAD

**Issue by kokekanon** [Nottinghster/otclient#13]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

"blessings"
https://github.com/Nottinghster/otclient/blob/new-layout/modules/game_mainpanel/mainpanel.lua#L475-L482

"expert pvp modes"
g_game.getFeature(GamePVPMode)? 
https://github.com/Nottinghster/otclient/blob/new-layout/modules/game_mainpanel/mainpanel.lua#L475-L482

"Customise Character"
https://github.com/Nottinghster/otclient/blob/new-layout/modules/game_interface/gameinterface.lua#L738

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
Fix -> [170a089](https://github.com/Nottinghster/otclient/commit/170a089e3aa1ee806ef1299c4b10ab3508a8c9a9)
