### ISSUE TITLE
bug: webscraping does not work on versions lower than php 82

### ISSUE THREAD

**Issue by GalaxyCLDev** [Nottinghster/otclient#18]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

When activating the API, it gives an error in the client when opening it and then connecting it also throws several errors all the time, maybe something was wrong

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
Did you set the correct status? (NO V8)

FAQ
![image](https://github.com/Nottinghster/otclient/assets/114332266/67b6e8e8-de78-4c10-8899-7b1adf1cd769)

**Comment by GalaxyCLDev** [comment]
![image](https://github.com/Nottinghster/otclient/assets/118214204/30907faa-9f5b-4d70-8655-cf4ab76584aa)

this happens if I put it

> Did you set the correct status? (NO V8)
> 
> FAQ ![image](https://private-user-images.githubusercontent.com/114332266/318212356-67b6e8e8-de78-4c10-8899-7b1adf1cd769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MTg2MDksIm5iZiI6MTcxMTgxODMwOSwicGF0aCI6Ii8xMTQzMzIyNjYvMzE4MjEyMzU2LTY3YjZlOGU4LWRlNzgtNGMxMC04ODk5LTdiMWFkZjFjZDc2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQxNzA1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzVmZTU5MTQ0MDNkYjI3ZDc3MmRhYTI3Y2M0ODY1YWY2ZTcyYTYyZjk3OTg3NWYzY2NmNGVlNDNiMGYzMGUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9_YeKPGtb0zsRIkNfgaywc4hFXst1ULL5IBIvPpanVI)

**Comment by kokekanon** [comment]
Are you sure you did this?


![image](https://github.com/Nottinghster/otclient/assets/114332266/af8fc058-84a7-45b3-b5d1-cff74d7fa837)

NO V8 status.php


did you use this one?
https://github.com/Nottinghster/otclient/blob/new-layout/tools/api/status.php


in C:\UniServerZ\www\api


![image](https://github.com/Nottinghster/otclient/assets/114332266/bda9eb01-f6b7-4a45-a598-4711f0fad801)

**Comment by GalaxyCLDev** [comment]
I use 74 because it is the one that appeared in the canary tutorial, should I change it?

> Are you sure you did this?
> 
> ![image](https://private-user-images.githubusercontent.com/114332266/318212590-af8fc058-84a7-45b3-b5d1-cff74d7fa837.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MTg5NDQsIm5iZiI6MTcxMTgxODY0NCwicGF0aCI6Ii8xMTQzMzIyNjYvMzE4MjEyNTkwLWFmOGZjMDU4LTg0YTctNDViMy1iNWQxLWNmZjc0ZDdmYTgzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQxNzEwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Nzc1OWJiZTgwMTY4MzNjODgzYTFmMzRiMjUwMGZiZGY3NmIzNzEyOTM0ZjdhZTViNTA3MTEyM2QzYWRiZTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PA8hgqd1xUJqs3E68AjhMUjv0IDQH2Wbse5h0_6ZvMA)
> 
> NO V8 status.php
> 
> did you use this one? https://github.com/Nottinghster/otclient/blob/new-layout/tools/api/status.php
> 
> in C:\UniServerZ\www\api
> 
> ![image](https://private-user-images.githubusercontent.com/114332266/318212574-bda9eb01-f6b7-4a45-a598-4711f0fad801.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MTg5NDQsIm5iZiI6MTcxMTgxODY0NCwicGF0aCI6Ii8xMTQzMzIyNjYvMzE4MjEyNTc0LWJkYTllYjAxLWY2YjctNGE0NS1hNTk4LTQ3MTFmMGZhZDgwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQxNzEwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjYzYzIwYzIwOTNiZjdiMDNmNjRkNzJhZDNmNzhiYzlkZDdmZTgxOGI1YzUyZTU3NTY0MThlMGQ2OGQ2YjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y7KUOM7So3qrrWZhwOpeInqJfC2RumRQcaqhgoi3WII)

**Comment by kokekanon** [comment]
no .
wait

**Comment by kokekanon** [comment]
try this temporary solution, you will not be able to see this. i will also change the error messages to print so that they are not so invasive
![image](https://github.com/Nottinghster/otclient/assets/114332266/6be7391b-1cb9-48e0-96b1-51fa97026351)

```php
<?php
$playersOnline = 0;
$data = json_decode(file_get_contents("php://input"));

//if(!$data) {
    // 
//}

$requestType = $data->type; 

// TOP MENU function EnterGame.postCacheInfo()

if ($requestType === 'cacheinfo') {
    if (version_compare(phpversion(), '8.2', '>=')) {
    try {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, "https://otarchive.com/server/62cde2f41770eac22ec6ad19");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); 
        curl_setopt($ch, CURLOPT_ENCODING , "");
        
        $site = curl_exec($ch);
        curl_close($ch);

        preg_match('/Informed Players (\d+) \(\d+\)/', $site, $matches);

        $doc = new DOMDocument();
        @$doc->loadHTML($site);

        $xpath = new DOMXPath($doc);


        $thElement = $xpath->query('//th[contains(text(), "Informed Players")]')->item(0);
        if ($thElement) {
           
            $tdElement = $thElement->nextSibling;
            if ($tdElement && $tdElement->nodeName === 'td') {
                $playersOnlineText = $tdElement->nodeValue;

                if (preg_match('/(\d+)/', $playersOnlineText, $matches)) {
                    $playersOnline = $matches[1];
                }
            }
        }
        $playersOnline = $matches[1];
    } catch(Exception $e) {}
} else {
 
    $playersOnline = 0;
}


    $online_discord = 0;
    try {
        $online_discord = json_decode(file_get_contents("https://discordapp.com/api/guilds/628769144925585428/widget.json"))->presence_count;
    } catch(Exception $e) {}

    $response = array(
        "playersonline" => "$playersOnline",
        "discord_online" => $online_discord,
        "discord_link" => "https://discord.gg/HZN8yJJSyC" ,
        "youtube_link" => "https://www.youtube.com/watch?v=6_2zizoJKxQ" ,
        "gamingyoutubestreams"=> "0", 
        "gamingyoutubeviewer"=> "0",
        "test" => $requestType,
    );
    echo json_encode($response);

// TOP MENU function EnterGame.postEventScheduler()

} elseif ($requestType === 'eventschedule') {
    // TEST
    $eventSchedulerCalendar = array(
        array(
            "startdate" => strtotime("2024-03-20"),
            "enddate" => strtotime("2024-03-25"),
            "colorlight" => "#FF0000",
            "colordark" => "#800000",
            "description" => "Descripcion del evento 1",
            "displaypriority" => 1,
            "isseasonal" => true,
            "name" => "Evento 1",
            "specialevent" => true
        ),
        array(
            "startdate" => strtotime("2024-04-01"),
            "enddate" => strtotime("2024-04-05"),
            "colorlight" => "#00FF00",
            "colordark" => "#008000",
            "description" => "Descripcion del evento 2",
            "displaypriority" => 2,
            "isseasonal" => false,
            "name" => "Evento 2",
            "specialevent" => false
        )
    );

    $response = array(
        "lastupdatetimestamp" => time(),
        "eventlist" => $eventSchedulerCalendar,
    );
    echo json_encode($response);
} 

//EnterGame.postShowOff()

elseif ($requestType === 'showoff') {


    $response = array(
        "image" => "https://raw.githubusercontent.com/mehah/otclient/main/data/images/clienticon.png",
        "title" => "OTClient - Redemption", 
        "description" => "Otclient is an alternative Tibia client for usage with otserv. It aims to be complete and flexible, for that it uses LUA scripting for all game interface functionality and configurations files with a syntax similar to CSS for the client interface design." 
    );
    echo json_encode($response);



   //  EnterGame.postShowCreatureBoost()
} elseif ($requestType === 'Creatureboost') {


    $response = array(
        "creature" => array(
            "type" => 222
        ),
        "boss" => array(
            "type" => 232
        )
    );
    echo json_encode($response);
} else {
    http_response_code(504); 
}
?>


```

**Comment by kokekanon** [comment]
delete this if 
 if (version_compare(phpversion(), '8.2', '>=')) {
 
 and active curl


![image](https://github.com/Nottinghster/otclient/assets/114332266/99ad2ce7-d70f-47f4-aa19-083140fb5814)




![image](https://github.com/Nottinghster/otclient/assets/114332266/84349388-a458-4eb5-b1d6-cce5693cfd5a)

**Comment by kokekanon** [comment]
test in 74 php  uniserverz

f0d5c51
a7dc783

if it does not work, re-open this issues or comment
