### ISSUE TITLE
FROZEN MONSTER

### ISSUE THREAD

**Issue by GalaxyCLDev** [Nottinghster/otclient#19]
### Priority

Critical

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

![image](https://github.com/Nottinghster/otclient/assets/118214204/925ec51a-3214-4a0b-b749-50b38f41edf3)
![image](https://github.com/Nottinghster/otclient/assets/118214204/d349cc00-a33c-4d29-b2d4-2d75b3076cc7)

I'm using Canary 13.32, and every time a player kills a creature this happens. It stays stuck for a few seconds and then it just falls, I don't know how to solve this and I don't know why it happens, some monsters that have already died also overlap and continue moving despite being dead, like they clone themselves.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GalaxyCLDev** [comment]
![image](https://github.com/Nottinghster/otclient/assets/118214204/18c29daf-dc17-46c1-a775-ab2bddb6d65e)
these errors in OTC console

**Comment by rodrigopaixaorj** [comment]
This issue will be closed for the following reason:

Our main goal with this fork, is working on the new layout and fix bugs related to it.
When we finish our goal here, we'll merge this fork with main repo of Mehah!

Only then, you guys should open issues related to protocols ;)
