### ISSUE TITLE
Textmessage does not appear / does not show

### ISSUE THREAD

**Issue by Levi999x** [Nottinghster/otclient#29]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

Text message does not appear on screen like

MESSAGE_STATUS_CONSOLE_ORANGE as example

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rodrigopaixaorj** [comment]
What version and engine are you using?

**Comment by kokekanon** [comment]
bbbf27d

![image](https://github.com/Nottinghster/otclient/assets/114332266/92e64061-6bc5-4136-93ed-00ec5a9d285a)
