### ISSUE TITLE
Stuck in SET OUTFIT window

### ISSUE THREAD

**Issue by mano368** [Nottinghster/otclient#33]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

TFS 1.5 nekiro downgrade 7.72

When you try to change outfit, the outfit window get stuck, also, no outfit is shown. Need to force exit to play again.

![Screenshot 2024-04-12 194752](https://github.com/Nottinghster/otclient/assets/53128315/8c715a0e-b339-4d97-b449-b217faf05ea5)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Levi999x** [comment]
any error code in terminal? ( CTRL + T )

**Comment by mano368** [comment]
> any error code in terminal? ( CTRL + T )

Open SetOutfit
![Screenshot 2024-04-13 130328](https://github.com/Nottinghster/otclient/assets/53128315/764106a3-a04f-48d7-abf1-e0889fdc3fab)

try to click cancel
![Screenshot 2024-04-13 130727](https://github.com/Nottinghster/otclient/assets/53128315/037c4542-5066-4856-a8ab-a89a2d7186f6)


try to click ok
![Screenshot 2024-04-13 130744](https://github.com/Nottinghster/otclient/assets/53128315/c39dc2a0-95a1-473a-9166-63027c31c305)

**Comment by kokekanon** [comment]
you need to compile new .exe
