### ISSUE TITLE
sometimes when opening the client the mini windows is bug

### ISSUE THREAD

**Issue by kojimhojo** [Nottinghster/otclient#38]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

sometimes when opening the client the mini windows is bug
to fix it , I have to clear the cache
![nitro5](https://github.com/Nottinghster/otclient/assets/164669689/7c868f4a-f7cb-4fa6-9c8e-5c8c04519fb5)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
That error has been in the main repo for a long time; it's not caused by the new layout.
