### ISSUE TITLE
PVP not working

### ISSUE THREAD

**Issue by rodrigopaixaorj** [Nottinghster/otclient#40]
### Priority

High

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

https://github.com/Nottinghster/otclient/assets/7372287/f9319026-1dff-41ad-a49d-bc82c638a0e1

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nottinghster** [comment]
https://github.com/Nottinghster/otclient/commit/0a88d92ae4c36507164e480f625a0174b090ef0f
