### ISSUE TITLE
BUG Entergame Version 13.32 Client 

### ISSUE THREAD

**Issue by lorencial** [Nottinghster/otclient#48]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

![Sem título](https://github.com/Nottinghster/otclient/assets/168190862/6a3fb78a-2a7b-4e02-9f18-845badc6df3f)

LINE 498
  if clientVersion >= 1281 and G.port ~= 7171 then
  
  ERRO
ERROR: /client_entergame/entergame.lua:498: attempt to compare number with nil

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
I think you're not using the 'new-layout' repository and you didn't compile with the latest update.

![image](https://github.com/Nottinghster/otclient/assets/114332266/7897253b-06d3-4adb-9d3c-37353a3e6ba4)
