### ISSUE TITLE
bug: when using extended view with new layout

### ISSUE THREAD

**Issue by kokekanon** [Nottinghster/otclient#7]
### Priority

Low

### Area

- [X] Data
- [ ] Source
- [ ] Docker
- [ ] Other

### What happened?

repo: new layout

report of : "ogabrielfroes" on discord

there is a problem in game_mainpanel with extended view

![image](https://github.com/Nottinghster/otclient/assets/114332266/96255349-70ef-43b6-a14e-1b25bbce60e1)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AzizsFroes** [comment]
![image](https://github.com/Nottinghster/otclient/assets/162846956/d5d55435-1763-44cd-b328-4e017460445a)
Aqui esta dando a mesma coisa
